name: Publish Extension
on:
  push:
    branches: main
    paths:
      - "src/**"
      - ".github/workflows/main.yaml"

env:
  GRAIN_CLIENT_ID: ${{ secrets.GRAIN_CLIENT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: build
        run: npm run build 
      - name: Publish
        run: aws s3 cp extension.js s3://production-grain-roam/extension.js
